### ISSUE TITLE
Chart - Needs Timeline

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#11]
Currently the Chart does not have a timeline functionality

**Comment by sam-ffctn** [comment]
We added the timeline to the chart, in the same way that it is on the map.
http://ffctn.com/clients/on/sfm/M13/#country/ng/o/147eb0bc-3516-4d3f-a5cb-fd9a396ed8ec!date=2014-01-01&focus=chart&overlay=

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn It doesn't seem like the timeline is functioning how I'd expect it - it doesn't seem to be reading the data from the organization. As an example I'm able to move the time slider to a random date in 2008, well before the first citation date and the organization is still displayed

![image](https://cloud.githubusercontent.com/assets/18744855/20978190/f64f54b4-bc75-11e6-88d2-dea556f120b1.png)

**Comment by sam-ffctn** [comment]
I'm not exactly sure what the intended behavior is for the timeline. When the timeline is set, we send a new call to the API with the selected date.
ex: https://sfm.datamade.us/api/organizations/1beedf1b-6c56-48d3-b086-6d33778a8691/chart/?at=2008-05-08

We simply render what that request returns. 
Right now I think the API will always return the same data no matter what date is set.

So I think this is an API bug.

**Comment by tonysecurityforcemonitor** [comment]
@evz can you take a look?

**Comment by evz** [comment]
Hmm, yes, this would be because that API endpoint isn't actually using the `at` parameter for anything. Woops. In this case, what is the correct date to use? We have several.

**Comment by tonysecurityforcemonitor** [comment]
@evz I envisioned the timeline working on both the Map and the Chart in the same way - the user would select a date and the Map and Chart would display what data the Monitor has for that date. By sliding the timeline the user could see the Map and Chart change as AOOs and Parent relationships change. If the user selected a time before or after the Monitor had data then the Chart or Map would be blank.

So for example - If the user selected 10 January 2012 the Joint Task Force from the screenshot above would be displayed on the Chart with the relevant parent/child hierarchy. The user could move the timeline through several years until they reached 23 June 2016 (we do not assume parent relationships, site or area of operations past 22 June 2016) and that Organization should disappear from the Chart and the Map.

**Comment by evz** [comment]
@tonysecurityforcemonitor I guess I should have made it clearer that question was mainly directed at you.

**Comment by evz** [comment]
So, it seems like the relevant dates for the map would be when an organization was active at a given site or in a given area?

**Comment by evz** [comment]
Hmm, it seems like a) I am really confusing myself and b) the API server seems to be really slow to load some of the things that the client parts are relying on. @sam-ffctn Does that seem right? (I mean the second part; I can tell you that the first part is true ;P ) If that is the case, I was thinking about provisioning some more resources for this app eventually anyways and can get that going probably early next week. Some of the functions seem to be doing the right thing, you just have to wait what seems like an unreasonable amount of time for them to load.

**Comment by sam-ffctn** [comment]
Ya this is mostly due to the map (the geometric data is quite huge). 
~ 15MB for https://sfm.datamade.us/api/countries/ng/geometries/
~ 1.2MB for https://sfm.datamade.us/api/countries/ng/map/?at=2014-01-01

I might be able to cache some stuff locally, but if you are playing with the timeline and select quite a few dates you could end up loading hundreds of megs of data.

**Comment by evz** [comment]
I don't know how flexible the client parts are but there is a `tolerance` parameter that you can send to the [`/countries/:id/geometries/`](https://github.com/security-force-monitor/sfm-proxy/blob/master/docs/miscellaneous.md#base-layers) endpoint that tells the response to simplify the geometries it returns. Under the hood it's using the [`ST_Simplify` function from PostGIS](http://www.postgis.org/docs/ST_Simplify.html) so, the closer the number is to 1, the less precision it retains. 

If something like that is useful, I can see about implementing it for the other endpoints that return geometries. You probably don't want to get too crazy with it otherwise it'll end up looking kinda terrible. Right now all of the geometries are simplified by default but very lightly so there is probably room for a bit more simplification. Let me know if an approach like that is something that you could use and we can experiment with it.

**Comment by sam-ffctn** [comment]
That would definitely help, wouldn't be hard to implement client side either.

**Comment by tonysecurityforcemonitor** [comment]
> So, it seems like the relevant dates for the map would be when an organization was active at a given site or in a given area?

@evz Exactly - the current thinking is that an organization's Site or Area of Operation should not be displayed before the respective date of first citation for those fields. Similarly if the Site or Area of Operation is not assumed to current date then they should not be displayed past the date of last citation.

**Comment by evz** [comment]
@sam-ffctn As discussed, I added a tolerance parameter to:

* `/countries/:id/search/organizations/`
* `/countries/:id/map/`
* `/events/:id/`
* `/organizations/:id/map/`
* `/organizations/:id/chart/`

**Comment by evz** [comment]
@tonysecurityforcemonitor So, one thing that I am not capturing from the spreadsheet is the "assume area of operations to current date" info. That said, it's simple enough to start grabbing. There's also another field in the spreadsheet (which I am grabbing) called `OrganizationSite:open_ended` which seems like a similar kind of thing but for the organization's site. Is that true? 

It sounds like the logic I am using to return info about organizations `at` at given point in time is a bit too liberal and is just ending up returning way too much. This includes attributes related not only to where they were at a given moment but also how they relate to other organizations and what their command structure and membership looked like. I'll adjust it. Once I make these updates, it might end up making the load time for the pages faster, too, since, hopefully, the amount of data being transferred over the wire will be smaller.

**Comment by tonysecurityforcemonitor** [comment]
> There's also another field in the spreadsheet (which I am grabbing) called OrganizationSite:open_ended which seems like a similar kind of thing but for the organization's site. Is that true?

@evz - Yep that's exactly right!

> It sounds like the logic I am using to return info about organizations at at given point in time is a bit too liberal and is just ending up returning way too much. This includes attributes related not only to where they were at a given moment but also how they relate to other organizations and what their command structure and membership looked like. I'll adjust it. Once I make these updates, it might end up making the load time for the pages faster, too, since, hopefully, the amount of data being transferred over the wire will be smaller.

I do want the attributes about command structure and membership to be displayed in the mini/full dossier and the Chart - I'm not sure if that effects the logic.

**Comment by evz** [comment]
I guess what I was getting at was that I am basically saying "give me everything where the start date is before a given date OR the end date is after that same date". It seems like that should be an AND most of the time and we should also be taking into account whether or not the relationship (to another organization or to a place) is open ended.

**Comment by tonysecurityforcemonitor** [comment]
@evz Ah ok that makes sense to me - thanks for the quick reply!

**Comment by evz** [comment]
One more, perhaps boneheaded question: Should the present and former commanders returned by the API for the chart view be relative to the date? So, should if a user is looking at what an organization looked like on 2011-01-01, should the `commander_present` be the commander on that date? Or the present commander? Same question for former commanders.

**Comment by tonysecurityforcemonitor** [comment]
Not boneheaded at all - I believe I'm the only one that has had some boneheaded questions ;)

> Should the present and former commanders returned by the API for the chart view be relative to the date? So, should if a user is looking at what an organization looked like on 2011-01-01, should the commander_present be the commander on that date? Or the present commander?

It would be great if it could be the commander on that date!

> Same question for former commanders.

That's a good question - I had a whole thing written out for how we could implement a change - but it got really complex fast. So, if possible, lets keep the former commanders in the Mini/Full Dossier the same - meaning displaying the most current commander and all other commanders listed under Former Commanders. So the name of the commander would just change in the Chart display as the user selects different dates, but not in the Mini/Full Dossier.

**Comment by evz** [comment]
OK, that makes sense. I am actually re-using some code under the hood that makes it so the API response for the chart also has the former commanders (even though they don't get used over there). Since this is going to be a slightly different query, I'll just make it so the chart response only returns the commander that was commander on the given date (and forget about the former commanders since it's not really used)

**Comment by evz** [comment]
So, I just updated the server so that the responses for the chart view should be relative to the date that the user is looking at.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor I'm not quite sure what the status of this issue is anymore. Is this issue resolved? Do we need to do anything on the client side?

**Comment by tonysecurityforcemonitor** [comment]
Thanks for following up @sam-ffctn - the chart doesn't seem to be returning data based on the selected date - http://ffctn.com/clients/on/sfm/M16/#country/ng/o/765f0a38-22d3-4115-86b3-0c03d829ae02!date=2012-08-08&focus=chart&overlay= --- The commander never changes, nor does any of the relationships between organizations.

Right now it appears to be static. Not sure if this is an issue for you @evz

**Comment by sam-ffctn** [comment]
@evz @tonysecurityforcemonitor To test this I would need to know 2 api calls that have different organizational relationships/commanders. Its possible that this may still be an issue on the client side, its just a bit difficult to test.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn I'm not sure if this is helpful - but I would test the 3 Armoured Division - http://ffctn.com/clients/on/sfm/M16/#country/ng/o/765f0a38-22d3-4115-86b3-0c03d829ae02!date=2014-01-01&focus=chart&classifications=Army&overlay=

The 3 Armoured Division has had 17 commanders since 14 March 1999

The 21 Armoured Brigade is a child of the 3 Armoured Division from 11 March 2002 until 18 August 2013. Expected functionality is that the relationship would be displayed between those two date points and not be displayed from 10 March 2002 to any point earlier and 19 August 2013 to any point later.

@evz Can you confirm that the parent/child relationship is in the CMS? I tried checking but wasn't able to see the dates on the main profile page of the 21 Armoured Brigade and when I selected Edit I didn't see the parent/child relationships displayed either. The information for the parent/child is in the Master Import Google Sheet however...

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz There seems to be a bug in the API for the chart when requesting the chart for 3 Armored Division this will in turn create bugs in the chart layout.

api request: https://sfm.datamade.us/api/organizations/765f0a38-22d3-4115-86b3-0c03d829ae02/chart/?at=2014-01-01 

The bug is in the parent/child relationship for the node `e6aea19b-8579-4e1d-8a15-4a326cbc0dd4`, this node has itself as a parent. 

I also noticed that there are duplicate nodes (all properties identical except for classification ) !? An example of this would be the node `4b67c29d-d4c3-4aed-8a8e-6a09e6e72bd5`.

For the chart to render properly we need to make sure that every node only has 1 parent so it can be rendered as a tree (we also don't want any detached nodes or cycles).

These issues can be quite difficult to identify on the front-end and take up a lot of resources. 

I'm not sure how many other nodes have similar issues.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz  - Just one quick note here - organizations can have more than 1 parent (not sure if that's what you mean by nodes) - generally this means an organization could have 2 parents (off the top of my head I can't think of any example of an organizations with 3 parents)

**Comment by evz** [comment]
@tonysecurityforcemonitor It looks like the problem that @sam-ffctn is describing above is actually reflected in the master import spreadsheet. If you scroll down to row 647, you'll see that there is an organization called "Special Task Force" that has the parent "Special Task Force". If these are somehow different special task forces, I guess we should figure out a convention for making them unique somehow.

**Comment by evz** [comment]
Wait, make that row 644. Sorry.

**Comment by tonysecurityforcemonitor** [comment]
@evz Ah I see - that's a mistake in the data. No organization can ever be it's own parent!

**Comment by tonysecurityforcemonitor** [comment]
@evz @sam-ffctn the mistake on row 644 has been fixed

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor Thanks for the fix.

@sebastien For the multiple parents, right now it's not possible for our graph/tree layout engine to render multiple parents, this would be a huge fix or we would need to switch to a different layout engine. I'm not sure if this was established earlier on in the project. It might be possible to get around this by only showing parts of the graph at any given time instead of what we are doing now which is building/revaling it as we navigate through it.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @sebastien - Can you describe a little bit more what it would mean about only showing parts of the graph at any given time?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @sebastien Also - just to clarify, is the issue an organization that has more than 1 parent at the same time, or an organization that has different parents over time, but only 1 parent at a time?

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor The issue is having multiple parent simultaneously, since we can no longer render the graph as a tree at that point. 

If we only show the immediate parents and children we might be able to get our layout engine to work with that, but I think that might make the chart useless since it won't show much information at all.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn Ah ok - let's do this then, I'll work to remove any organization that has multiple parents at the same time so we don't trigger this issue (it's a very, very small number of organizations). I'm reviewing the data now and will work with @evz to pull out the conflicts.

**Comment by sam-ffctn** [comment]
@evz The API now seems to be missing some parent nodes in the request

ex: 
https://sfm.datamade.us/api/organizations/5a8e5e4b-5669-49a4-a500-eefd93111e29/chart/?at=2014-01-01
references the node: 19ad99a4-9db8-49a0-8a03-bf6a78be872c 
but that node is nowhere to be found in the data

another example:

this [request](https://sfm.datamade.us/api/organizations/acc51404-b07c-430b-895a-88c4c63d305e/chart/?at=2014-01-01) is missing these nodes:
-  3caa62a3-821a-4eca-8e47-ed7d4adf2fb6
- 7b18947c-792b-460a-b711-fd73c7aaa2b0
- 19ad99a4-9db8-49a0-8a03-bf6a78be872c

**Comment by evz** [comment]
So, hmm, I'm a little confused. What do you mean by "nowhere to be found"? I found them:

https://sfm.datamade.us/api/organizations/3caa62a3-821a-4eca-8e47-ed7d4adf2fb6/
https://sfm.datamade.us/api/organizations/7b18947c-792b-460a-b711-fd73c7aaa2b0/
https://sfm.datamade.us/api/organizations/19ad99a4-9db8-49a0-8a03-bf6a78be872c/

It's possible that the application cache cached something poorly when you were trying to access these before but when I think through that, I'm not sure that's possible in this case since these are very specific URLs. Did you get a 404 response? Or was it a different error? I'd like to make sure that this is not a deeper problem.

**Comment by sam-ffctn** [comment]
@evz I mean they aren't found in the parent or children in the /organizations/:id/chart endpoint, I know it can be found by directly requesting it. 
As far as I understand the parents property contains a list of the parents all the way up to the root, and the children are all the children, not just the direct descendants. If this is the case then it shouldn't be possible for a node to reference another node not contained in the parents or children.

**Comment by evz** [comment]
Oh, I see. Let me dig a bit deeper.

**Comment by evz** [comment]
So, I have yet to find the root cause of this. I am unable to reproduce it in my local development stack which makes me think it's somehow just an issue with the data loader. I am in the process of recreating those tables now in an attempt to make clean it up.

**Comment by evz** [comment]
OK, I think I excised the demons here. It came down to the database on the server just needing a full refresh. I'll need to think a bit more about how I want to perform updates from the Google Doc (but hopefully that won't be needed for much longer)

**Comment by tonysecurityforcemonitor** [comment]
Thanks @evz ! Yes we will be getting away from using the Master Import Sheet soon enough. There are a couple of outstanding issues that are on my plate regarding the Sheet that I'm hoping to bang out soon (next day or two).

**Comment by tonysecurityforcemonitor** [comment]
Just did some testing with http://ffctn.com/clients/on/sfm/M19/#country/ng/o/e7d0a9ac-708c-495d-b5da-5ce1a9fe08ee!date=2012-11-30&focus=chart&classifications=Army&overlay= -- this seems to be working quite well!
