### ISSUE TITLE
Person Mini Dossier/Full Dossier - need to remove place of birth and death date

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#16]
@sam-ffctn - The mini dossier and full dossiers for people have a birth place and death date listed - the Monitor doesn't capture data on either of these things currently so they should be removed from the UI.

**Comment by sam-ffctn** [comment]
these fields our now removed
http://ffctn.com/clients/on/sfm/M14/#country/ng/p/705c584e-5316-4cf6-b13b-400453bf53df!date=2014-01-01&focus=map

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz An API error is preventing me from testing this

**Comment by evz** [comment]
@sam-ffctn Could you explain a bit how that error is being returned? It looks like just visiting the URL from the error message returns the response you'd expect. One thing I notice is that the URL in the error message is missing the trailing slash after the person ID so it's 

https://sfm.datamade.us/api/people/705c584e-5316-4cf6-b13b-400453bf53df

instead of:

https://sfm.datamade.us/api/people/705c584e-5316-4cf6-b13b-400453bf53df/

a subtle difference and the application server does do a 301 redirect but I'm not sure if the client side code is setup to handle that.

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn @evz This seems to have been resolved
