### ISSUE TITLE
Map/Dossiers - Peacekeeping orgs/people not displaying

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#42]
@evz clicking on Sierra Leon, DRC or Liberia (example link: http://ffctn.com/clients/on/sfm/M19/#country/lr!date=2014-01-01) brings up a blank map with no Organizations.

I'm not sure if this is an API or data issue.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @evz 

The API requests for these countries comeback completely empty.

ex:
https://sfm.datamade.us/api/countries/sl/map/?tolerance=0.01&at=2014-01-01
https://sfm.datamade.us/api/countries/cd/map/?tolerance=0.01&at=2014-01-01
https://sfm.datamade.us/api/countries/lr/map/?tolerance=0.01&at=2014-01-01

**Comment by tonysecurityforcemonitor** [comment]
@evz Let me know if there is anything that needs to be fixed on the data side of things with this - I suspect that could be part of the problem.

**Comment by evz** [comment]
@tonysecurityforcemonitor So, I've managed to get the UN missions in Congo to show up when you put in a date that makes sense: 

Stabilization mission: https://sfm.datamade.us/api/countries/cd/map/?tolerance=0.01&at=2014-01-01
Earlier mission https://sfm.datamade.us/api/countries/cd/map/?tolerance=0.01&at=2010-01-01

However, the country map view replies on the organization having a Site. If there's no Site, it gets filtered out. This is because we need to rely on some kind of date to know that the organization was in a particular place at a particular time. In these cases we don't have a site:

* Military Observer Group in Liberia (row 652)
* Nigerian Battalion 14 (UNIMIL) (row 653)
* United Nations Mission in Liberia (row 654)
* United Nations Mission in Sierra Leone (row 837)

**Comment by tonysecurityforcemonitor** [comment]
@evz Ok that's helpful to know. I can get Sites for the UN missions in Liberia and Sierra Leone, rows 652 and 653 might be more tricky (but worst case I'll just remove them from the data sheet). I'll fix this with the next update to the Master Import Sheet later this week.
