### ISSUE TITLE
Dead end on person dossier when selecting item in job history

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#68]
Starting here:

http://ffctn.com/clients/on/sfm/M27/#country/mx/o/953284a9-0961-475f-8a8b-66c01f9d53f8/p/953284a9-0961-475f-8a8b-66c01f9d53f8!date=2013-01-17&focus=chart&perspective=organizations

Select ```3 Zona Militar``` or ```13 Zona Militar``` in the mini-dossier. The app hangs for me.

**Comment by tonysecurityforcemonitor** [comment]
Hmm - I can't get it to load at all... @evz is there data issue here? @sam-ffctn can you also take a look?

**Comment by evz** [comment]
There's no organization with that ID. What was the name of the organization you were trying to look at?

**Comment by evz** [comment]
I'm actually unable to get that link to load either. When I inspect the resources that the page is loading it's trying to get an organization from this endpoint: 

https://sfm.datamade.us/api/organizations/953284a9-0961-475f-8a8b-66c01f9d53f8/

Which is empty. I'm not sure what organization it's trying to load. I can get both `3 Zona Militar` and `13 Zona Militar` to load by searching for them but I think that's not really the issue here. @tlongers Any chance you could let me know how you ended up on that starting URL in the first place?

**Comment by tlongers** [comment]
Ah, I don't have the full history - it just hung at some point. I related #77 to this which might help figure it out.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers @evz This issue should now be solved.The front end was using the membership id which seems to no longer correspond with organization id. I'm now using the organization id listed under `organization_id.value`

http://ffctn.com/clients/on/sfm/M28/

**Comment by tonysecurityforcemonitor** [comment]
@tlongers - can you do a quick test here? You're navigating through with different eyes which has been really helpful to spot issues like this.

**Comment by tlongers** [comment]
Fixed, thanks @sam-ffctn @evz
