### ISSUE TITLE
Default time slider date

### ISSUE THREAD

**Issue by tlongers** [security-force-monitor/sfm-ui#69]
The default date for the time slider is ```2014-01-01```. This is arbitrary. Could the default date on the time sliders be either:

*  the current date;
*  the last date the user was looking at before leaving the Monitor; or
*  the date of the last entry in the Monitor for whichever country the user is viewing.

@tonysecurityforcemonitor any thoughts? Or leave for now?

**Comment by tonysecurityforcemonitor** [comment]
@sam-ffctn can we set it to the current date? There are some rough data patches that setting to the current date will smooth over (as the user will have to dig to hit them, rather than being presented to them initially).  If setting to the current date is an issue, can we pick 2017-03-20 as the new arbitrary date? This will achieve the same ends.

**Comment by sam-ffctn** [comment]
@tonysecurityforcemonitor @tlongers The timeline now uses the current date as the default

http://ffctn.com/clients/on/sfm/M28/#country/mx

**Comment by tonysecurityforcemonitor** [comment]
Thanks @sam-ffctn
