### ISSUE TITLE
Mini Dossier/Full Dossier - No click through to Commander

### ISSUE THREAD

**Issue by tonysecurityforcemonitor** [security-force-monitor/sfm-ui#9]
From an Organization's mini-dossier on the Map page, or their full dossier I would expect to be able to click on a Commander's name and be taken to their dossier - this functionality doesn't exist

**Comment by sam-ffctn** [comment]
The commanders name is now clickable (both in the mini dossier and full dossier). There seems to be some rendering issues with some of the data (I will look into this tomorrow, it is most likely due to API changes).
http://ffctn.com/clients/on/sfm/M13/#country/ng/o/147eb0bc-3516-4d3f-a5cb-fd9a396ed8ec!date=2014-01-01&focus=map
